title: Resources for Seniors
description: Information for Seniors
baseurl: "/seniors/" # the subpath of your site, e.g. /blog
url: "https://info.waterlooregion.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

remote_theme: pmarsceill/just-the-docs

